name: First workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Hello!
        run: echo "Hello!!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

      - name: Runing Linter!!!
        run: |
          echo npm run lint
          echo "Code checked!"

      - name: Prettier
        run: |
          npm run format
          echo "Formated!"
